# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/HosnaJabbari/HFold

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/HosnaJabbari/HFold

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/HosnaJabbari/HFold/CMakeFiles /home/user/HosnaJabbari/HFold//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/HosnaJabbari/HFold/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HFold

# Build rule for target.
HFold: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HFold
.PHONY : HFold

# fast build rule for target.
HFold/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/build
.PHONY : HFold/fast

src/HFold.o: src/HFold.cpp.o
.PHONY : src/HFold.o

# target to build an object file
src/HFold.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/HFold.cpp.o
.PHONY : src/HFold.cpp.o

src/HFold.i: src/HFold.cpp.i
.PHONY : src/HFold.i

# target to preprocess a source file
src/HFold.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/HFold.cpp.i
.PHONY : src/HFold.cpp.i

src/HFold.s: src/HFold.cpp.s
.PHONY : src/HFold.s

# target to generate assembly for a file
src/HFold.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/HFold.cpp.s
.PHONY : src/HFold.cpp.s

src/Hotspot.o: src/Hotspot.cpp.o
.PHONY : src/Hotspot.o

# target to build an object file
src/Hotspot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Hotspot.cpp.o
.PHONY : src/Hotspot.cpp.o

src/Hotspot.i: src/Hotspot.cpp.i
.PHONY : src/Hotspot.i

# target to preprocess a source file
src/Hotspot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Hotspot.cpp.i
.PHONY : src/Hotspot.cpp.i

src/Hotspot.s: src/Hotspot.cpp.s
.PHONY : src/Hotspot.s

# target to generate assembly for a file
src/Hotspot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Hotspot.cpp.s
.PHONY : src/Hotspot.cpp.s

src/Result.o: src/Result.cpp.o
.PHONY : src/Result.o

# target to build an object file
src/Result.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Result.cpp.o
.PHONY : src/Result.cpp.o

src/Result.i: src/Result.cpp.i
.PHONY : src/Result.i

# target to preprocess a source file
src/Result.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Result.cpp.i
.PHONY : src/Result.cpp.i

src/Result.s: src/Result.cpp.s
.PHONY : src/Result.s

# target to generate assembly for a file
src/Result.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/Result.cpp.s
.PHONY : src/Result.cpp.s

src/W_final.o: src/W_final.cpp.o
.PHONY : src/W_final.o

# target to build an object file
src/W_final.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/W_final.cpp.o
.PHONY : src/W_final.cpp.o

src/W_final.i: src/W_final.cpp.i
.PHONY : src/W_final.i

# target to preprocess a source file
src/W_final.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/W_final.cpp.i
.PHONY : src/W_final.cpp.i

src/W_final.s: src/W_final.cpp.s
.PHONY : src/W_final.s

# target to generate assembly for a file
src/W_final.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/W_final.cpp.s
.PHONY : src/W_final.cpp.s

src/cmdline.o: src/cmdline.cpp.o
.PHONY : src/cmdline.o

# target to build an object file
src/cmdline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/cmdline.cpp.o
.PHONY : src/cmdline.cpp.o

src/cmdline.i: src/cmdline.cpp.i
.PHONY : src/cmdline.i

# target to preprocess a source file
src/cmdline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/cmdline.cpp.i
.PHONY : src/cmdline.cpp.i

src/cmdline.s: src/cmdline.cpp.s
.PHONY : src/cmdline.s

# target to generate assembly for a file
src/cmdline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/cmdline.cpp.s
.PHONY : src/cmdline.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pseudo_loop.o: src/pseudo_loop.cpp.o
.PHONY : src/pseudo_loop.o

# target to build an object file
src/pseudo_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/pseudo_loop.cpp.o
.PHONY : src/pseudo_loop.cpp.o

src/pseudo_loop.i: src/pseudo_loop.cpp.i
.PHONY : src/pseudo_loop.i

# target to preprocess a source file
src/pseudo_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/pseudo_loop.cpp.i
.PHONY : src/pseudo_loop.cpp.i

src/pseudo_loop.s: src/pseudo_loop.cpp.s
.PHONY : src/pseudo_loop.s

# target to generate assembly for a file
src/pseudo_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/pseudo_loop.cpp.s
.PHONY : src/pseudo_loop.cpp.s

src/s_energy_matrix.o: src/s_energy_matrix.cpp.o
.PHONY : src/s_energy_matrix.o

# target to build an object file
src/s_energy_matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/s_energy_matrix.cpp.o
.PHONY : src/s_energy_matrix.cpp.o

src/s_energy_matrix.i: src/s_energy_matrix.cpp.i
.PHONY : src/s_energy_matrix.i

# target to preprocess a source file
src/s_energy_matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/s_energy_matrix.cpp.i
.PHONY : src/s_energy_matrix.cpp.i

src/s_energy_matrix.s: src/s_energy_matrix.cpp.s
.PHONY : src/s_energy_matrix.s

# target to generate assembly for a file
src/s_energy_matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/s_energy_matrix.cpp.s
.PHONY : src/s_energy_matrix.cpp.s

src/sparse_tree.o: src/sparse_tree.cpp.o
.PHONY : src/sparse_tree.o

# target to build an object file
src/sparse_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/sparse_tree.cpp.o
.PHONY : src/sparse_tree.cpp.o

src/sparse_tree.i: src/sparse_tree.cpp.i
.PHONY : src/sparse_tree.i

# target to preprocess a source file
src/sparse_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/sparse_tree.cpp.i
.PHONY : src/sparse_tree.cpp.i

src/sparse_tree.s: src/sparse_tree.cpp.s
.PHONY : src/sparse_tree.s

# target to generate assembly for a file
src/sparse_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HFold.dir/build.make CMakeFiles/HFold.dir/src/sparse_tree.cpp.s
.PHONY : src/sparse_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... HFold"
	@echo "... src/HFold.o"
	@echo "... src/HFold.i"
	@echo "... src/HFold.s"
	@echo "... src/Hotspot.o"
	@echo "... src/Hotspot.i"
	@echo "... src/Hotspot.s"
	@echo "... src/Result.o"
	@echo "... src/Result.i"
	@echo "... src/Result.s"
	@echo "... src/W_final.o"
	@echo "... src/W_final.i"
	@echo "... src/W_final.s"
	@echo "... src/cmdline.o"
	@echo "... src/cmdline.i"
	@echo "... src/cmdline.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pseudo_loop.o"
	@echo "... src/pseudo_loop.i"
	@echo "... src/pseudo_loop.s"
	@echo "... src/s_energy_matrix.o"
	@echo "... src/s_energy_matrix.i"
	@echo "... src/s_energy_matrix.s"
	@echo "... src/sparse_tree.o"
	@echo "... src/sparse_tree.i"
	@echo "... src/sparse_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

