package:
  name: hfold
  version: "1.0.1"

source:
  - path: ..
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.1
    - python>=3.8
  host:
    - viennarna
    - libstdcxx-ng # [linux]
    - libcxx       # [osx]
  run:
    - viennarna
    - python>=3.8
    - libstdcxx-ng # [linux]
    - libcxx       # [osx]

about:
  home: https://github.com/HosnaJabbari/HFold
  license: "MIT"
  license_file: LICENSE
  summary: "HFold is an algorithm for predicting pseudoknotted secondary structures of RNA using strict Hierarchical Folding."
  description: |
    HFold predicts RNA secondary structure using a hierarchical folding approach.
  dev_url: https://github.com/HosnaJabbari/HFold

extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - HFold --help